### ISSUE TITLE
[1.17.1] Greater Eye doesn't work with YUNG's BetterStrongHold

### ISSUE THREAD

**Issue by superdumpling** [kwpugh/greater_eye_fabric#1]
I set it to stronghold, right clicked and it doesn't fire, looked in logs and found

[14:02:41] [Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10263()" because "locpos" is null
	at com.kwpugh.greater_eye.items.ItemGreaterEye.findStructureAndShoot(ItemGreaterEye.java:135) ~[GreaterEye-Fabric-1.17.1-1.2.7.jar:?]
	at com.kwpugh.greater_eye.items.ItemGreaterEye.method_7836(ItemGreaterEye.java:113) ~[GreaterEye-Fabric-1.17.1-1.2.7.jar:?]
	at net.minecraft.class_1799.method_7913(class_1799.java:254) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3225.method_14256(class_3225.java:282) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3244.method_12065(class_3244.java:1086) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_2886.method_12550(class_2886.java:25) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_2886.method_11054(class_2886.java:7) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:38) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:193) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:158) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:171) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by kwpugh** [comment]
Are you using a mod that replaces the vanilla stronghold?

**Comment by kwpugh** [comment]
Opened issue with Better Stronghold mod.  Also, latest Greater Eye Mod has a null check and will display a message that the Stronghold was replaced.

https://github.com/yungnickyoung/YUNGs-Better-Strongholds/issues/34

**Comment by kwpugh** [comment]
FYI, nothing I can do when mods remove/replace vanilla structures.  It is up to YUNG's to do something, if anything.

**Comment by kwpugh** [comment]
The author of BetterStrongHolds is not planning to fix the problem, so nothing can be done on my end.
